version: '3.8'

services:
  postgres:
    image: samucation/postgres-m33:latest
    container_name: postgres
    environment:
      POSTGRES_DB: m33_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: F7@uM!dQ#2kLpZxT$9eV
    ports:
      - "5432:5432"
    networks:
      - fixyou-network

  keycloak:
    image: samucation/keycloak:latest
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/m33_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: F7@uM!dQ#2kLpZxT$9eV
      KC_HOSTNAME: 192.168.1.16
      KC_HOSTNAME_STRICT: false
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./keycloak-data:/opt/keycloak/data
    networks:
      - fixyou-network

  flyway:
    image: flyway/flyway:9.16.0
    container_name: flyway
    depends_on:
      - postgres
    volumes:
      - ./registrations/src/main/resources/db/migration:/flyway/sql
    command: -url=jdbc:postgresql://postgres:5432/m33_db -user=postgres -password=F7@uM!dQ#2kLpZxT$9eV -schemas=fixyou -defaultSchema=fixyou migrate
    networks:
      - fixyou-network

  app:
    build: .
    container_name: fixyou_app
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - keycloak
    environment:
      APPLICATION_ENVIRONMENT: local
      JDBC_DATABASE_URL: jdbc:postgresql://postgres:5432/m33_db
      JDBC_DATABASE_USERNAME: postgres
      JDBC_DATABASE_PASSWORD: F7@uM!dQ#2kLpZxT$9eV
      ENV_FILE: docker-NBQFC-3S0L1M3
      ENV_PATH: /app/env
      KEYCLOAK_URL: http://192.168.1.16:8080/
      KEYCLOAK_REALM: fixyou-realm
      FLYWAY_DEFAULT_SCHEMA: fixyou
      FLYWAY_SCHEMAS: fixyou
    networks:
      - fixyou-network

networks:
  fixyou-network:
    external: true

