version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fixyou-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: m33_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${JDBC_DATABASE_PASSWORD}"
    volumes:
      - fixyou-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fixyou-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: samucation/keycloak:latest
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/m33_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: "${JDBC_DATABASE_PASSWORD}"
      KC_HOSTNAME: 192.168.15.25
      KC_HOSTNAME_STRICT: false
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./keycloak-data:/opt/keycloak/data
    networks:
      - fixyou-network

  flyway:
    image: flyway/flyway:10
    container_name: flyway
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      -locations=filesystem:/flyway/sql
      -url=jdbc:postgresql://postgres:5432/m33_db
      -user=postgres
      -password=${JDBC_DATABASE_PASSWORD}
      -schemas=fixyou
      migrate
    volumes:
      - ./registrations/src/main/resources/db/migration:/flyway/sql
    networks:
      - fixyou-network


  fixyou_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fixyou-app
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    env_file:
      - .env
    environment:
      ENV_FILE: .env
      ENV_PATH: /app/env
    volumes:
      - ./.env:/app/env/.env
    networks:
      - fixyou-network

volumes:
  fixyou-pgdata:

networks:
  fixyou-network:
    driver: bridge
