version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: m33_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: F7@uM!dQ#2kLpZxT$9eV
    ports:
      - "5432:5432"

  keycloak:
    image: samucation/keycloak:latest
    container_name: keycloak
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/m33_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: F7@uM!dQ#2kLpZxT$9eV
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  app:
    build: .
    container_name: fixyou_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://postgres:5432/m33_db
      JDBC_DATABASE_USERNAME: postgres
      JDBC_DATABASE_PASSWORD: F7@uM!dQ#2kLpZxT$9eV
      ENV_FILE: docker
      ENV_PATH: /app/env
      KEYCLOAK_URL: http://keycloak:8081/
      KEYCLOAK_REALM: fixyou-realm
