-- Tabela Profile
CREATE TABLE fixyou.tb_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit VARCHAR(100),
    department VARCHAR(100),
    preferred_shift VARCHAR(100),
    job_title VARCHAR(100)
);

-- Tabela Role
CREATE TABLE fixyou.tb_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- Tabela User
CREATE TABLE fixyou.tb_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    profile_id BIGINT NOT NULL,
    CONSTRAINT fk_profile FOREIGN KEY (profile_id) REFERENCES fixyou.tb_profile(id)
);

-- Tabela Intermediária User <-> Roles
CREATE TABLE fixyou.tb_user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES fixyou.tb_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES fixyou.tb_roles(id) ON DELETE CASCADE
);
